packages:
  - ./common/core
  - ./common/backend
  - ./basic/cdk
  - ./basic/app
  - ./basic/cdk/function
  - ./rag/batch
  - ./rag/app
  - ./rag/cdk
  - ./rag/cdk/function
  - ./webllm
  - ./node-llama-cpp
  - ./agents/agent-mastra
  - ./agents/agent-voltagent
  - ./mcp/servers/postgresql-http
  - ./mcp/servers/weather
  - ./mcp/servers/weather-http
  - ./mcp/servers/resource-mcp-server
  - ./mcp/clients/mcp-client-typescript
  - ./mcp/clients/mcp-client-http
  - ./mcp/clients/langgraph-mcp-client
  - ./mcp/clients/mastra-mcp-client

auto-install-peers: true

enable-pre-post-scripts: true

legacy-peer-deps: true

onlyBuiltDependencies:
  - esbuild
  - node-llama-cpp
  - protobufjs
  - sharp
  - unrs-resolver

overrides:
  axios@=1.10.0: '>=1.11.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  got@<11.8.5: '>=11.8.5'
  tmp@<=0.2.3: '>=0.2.4'
  chalk@5.6.2: '>=5.6.2'
  jsondiffpatch@<0.7.2: '>=0.7.2'

strict-peer-dependencies: false

# # one day
# minimumReleaseAge: 1440
# minimumReleaseAgeExclude:
#  - pnpm
