packages:
  - ./basic/cdk
  - ./basic/app
  - ./basic/cdk/function
  - ./rag/batch
  - ./rag/app
  - ./rag/cdk
  - ./rag/cdk/function
  - ./webllm
  - ./node-llama-cpp
  - ./agent-mastra
  - './mpc/weather'
  - './mpc/mcp-client-typescript'
  - './mpc/langgraph-mpc-client'

onlyBuiltDependencies:
  - esbuild
  - node-llama-cpp
  - protobufjs
  - sharp
