packages:
  - ./basic/cdk
  - ./basic/app
  - ./basic/cdk/function
  - ./rag/batch
  - ./rag/app
  - ./rag/cdk
  - ./rag/cdk/function
  - ./webllm
  - ./node-llama-cpp
  - ./agent-mastra
  - './mpc/servers/weather'
  - './mpc/servers/weather-http'
  - './mpc/clients/mcp-client-typescript'
  - './mpc/clients/mcp-client-http'
  - './mpc/clients/langgraph-mpc-client'
  - './mpc/clients/mastra-mcp-client'

onlyBuiltDependencies:
  - esbuild
  - node-llama-cpp
  - protobufjs
  - sharp

enable-pre-post-scripts: true
legacy-peer-deps: true
auto-install-peers: true
strict-peer-dependencies: false
