packages:
  - ./common/core
  - ./common/backend
  - ./basic/cdk
  - ./basic/app
  - ./basic/cdk/function
  - ./rag/batch
  - ./rag/app
  - ./rag/cdk
  - ./rag/cdk/function
  - ./agents/agent-mastra
  - ./agents/agent-claude-agent-sdk
  - ./agents/agent-strands
  - ./agents/agent-langchain
  - ./agents/agent-langchain-nextjs
  - ./mcp/servers/postgresql-http
  - ./mcp/servers/weather
  - ./mcp/servers/weather-http
  - ./mcp/servers/resource-mcp-server
  - ./mcp/clients/mcp-client-typescript
  - ./mcp/clients/mcp-client-http
  - ./mcp/clients/mastra-mcp-client
  - ./chat-app

autoInstallPeers: true

enablePrePostScripts: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

legacyPeerDeps: true

onlyBuiltDependencies:
  - esbuild
  - protobufjs

overrides:
  '@modelcontextprotocol/sdk@<1.24.0': '>=1.24.0'
  ai@<5.0.52: '>=5.0.52'
  axios@<1.10.0: '>=1.11.0'
  chalk@5.6.2: '>=5.6.2'
  fast-xml-parser@<=5.3.3: '>=5.3.4'
  form-data@<4.0.4: '>=4.0.4'
  glob@<=11.0.3: '>=11.1.0'
  got@<11.8.5: '>=11.8.5'
  hono@<4.10.2: '>=4.10.2'
  jsondiffpatch@<0.7.2: '>=0.7.2'
  lodash-es@<=4.17.22: '>=4.17.23'
  playwright@<1.55.1: '>=1.55.1'
  seroval@<=1.4.0: '>=1.4.1'
  tmp@<=0.2.3: '>=0.2.4'
  # eslint: ">=10.0.0"
  # '@eslint/js': ">=10.0.0"
  '@stylistic/eslint-plugin': '>=5.0.0'

strictPeerDependencies: false
