export const models = [
  {
    id: 'nova-micro',
    name: 'Amazon Nove Micro (Amazon Bedrock)',
    modelId: 'us.amazon.nova-micro-v1:0',
    selected: true,
    platform: 'aws',
  },
  {
    id: 'nova-lite',
    name: 'Amazon Nove Lite (Amazon Bedrock)',
    modelId: 'us.amazon.nova-lite-v1:0',
    selected: false,
    platform: 'aws',
  },
  {
    id: 'nova-pro',
    name: 'Amazon Nove Pro (Amazon Bedrock)',
    modelId: 'us.amazon.nova-pro-v1:0',
    selected: false,
    platform: 'aws',
  },
  {
    id: 'nova-premier',
    name: 'Amazon Nove Premier (Amazon Bedrock)',
    modelId: 'us.amazon.nova-premier-v1:0',
    selected: false,
    platform: 'aws',
  },
  {
    id: 'gpt-oss-20b',
    name: 'OpenAI gpt-oss-20b (Amazon Bedrock)',
    modelId: 'openai.gpt-oss-20b-1:0',
    disabled: true,
    selected: false,
    platform: 'aws',
  },
  {
    id: 'gpt-oss-120b',
    name: 'OpenAI gpt-oss-120b (Amazon Bedrock)',
    modelId: 'openai.gpt-oss-120b-1:0',
    disabled: true,
    selected: false,
    platform: 'aws',
  },
  {
    id: 'gpt-5-mini',
    name: 'GPT-5-mini',
    modelId: 'gpt-5-mini',
    selected: false,
    platform: 'azure',
  },
  {
    id: 'gpt-5-nano',
    name: 'GPT-5-nano',
    modelId: 'gpt-5-nano',
    selected: false,
    platform: 'azure',
  },
];
