services:
  neo4j:
    user: neo4j:neo4j
    image: neo4j
    ports:
        - 7474:7474
        - 7687:7687
    environment:
      - 'NEO4J_AUTH=neo4j/password'
      - 'NEO4JLABS_PLUGINS=["apoc"]'
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
