packages:
  - .

auto-install-peers: true

enable-pre-post-scripts: true

legacy-peer-deps: true

onlyBuiltDependencies:
  - esbuild
  - node-llama-cpp
  - protobufjs
  - sharp
  - unrs-resolver

overrides:
  axios@=1.10.0: '>=1.11.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  got@<11.8.5: '>=11.8.5'
  tmp@<=0.2.3: '>=0.2.4'

strict-peer-dependencies: false
